# GDB may have ./.gdbinit loading disabled by default.  In that case you can
# follow the instructions it prints.  They boil down to adding the following to
# your home directory's ~/.gdbinit file:
#
#   add-auto-load-safe-path /path/to/qemu/.gdbinit

# Load QEMU-specific sub-commands and settings
source scripts/qemu-gdb.py
b vcpu_insn_exec_before
#run --plugin ./tests/tcg/plugins/libvirtual.so,monitor=../ws/monitor.elf,logger=ws/log_config.txt,virtual=ws/virtuals.txt,detour=ws/detours.txt,modifier=ws/modifiers.txt -d in_asm,op -D qemu.log -machine mps2-an385 -monitor telnet:127.0.0.1:5555,server,nowait -semihosting --semihosting-config enable=on,target=native -qmp unix:/tmp/qmp-sock,server,nowait -kernel ../ws/RTOSDemo.axf -serial stdio -nographic -gdb tcp::1235 -S

# run --plugin ./tests/tcg/plugins/libvirtual.so,monitor=../ws/monitor.elf,logger=ws/log_config.txt,virtual=ws/virtuals.txt,detour=ws/detours.txt,modifier=ws/modifiers.txt -d in_asm,op -D qemu.log -machine pixhawk1 -monitor telnet:127.0.0.1:5555,server,nowait -semihosting --semihosting-config enable=on,target=native -qmp unix:/tmp/qmp-sock,server,nowait -kernel ../ws/RTOSDemo.axf -serial stdio -nographic -gdb tcp::1235 -S

#run --plugin ./tests/tcg/plugins/libvirtual.so -machine mps2-an385 -monitor null -kernel ws/RTOSDemo.axf -serial stdio -nographic

# m4_debug
# run --plugin ./tests/tcg/plugins/libvirtual.so,logger=ws/log_config.txt,virtual=ws/virtuals.txt,detour=ws/detours.txt,modifier=ws/modifiers.txt,args=ws/rand_setting.json,outs=ws/out_setting.json,basicblocks=ws/bb.txt -d in_asm,op -D qemu.log -machine pixhawk1 -monitor telnet:127.0.0.1:5555,server,nowait -semihosting --semihosting-config enable=on,target=native -qmp unix:/tmp/qmp-sock,server,nowait -kernel ../ws/m4_debug -serial stdio -nographic -gdb tcp::1235 -S

# gs3
# run --plugin ./tests/tcg/plugins/libvirtual.so,logger=ws/log_config.txt,virtual=ws/virtuals.txt,detour=ws/detours.txt,modifier=ws/modifiers.txt,args=ws/rand_setting.json,outs=ws/out_setting.json,basicblocks=ws/bb.txt -d in_asm,op -D qemu.log -machine cortexm,memory-backend=ram0 -monitor telnet:127.0.0.1:5555,server,nowait -semihosting --semihosting-config enable=on,target=native -qmp unix:/tmp/qmp-sock,server,nowait -object memory-backend-file,id=ram0,mem-path=/dev/shm/my_m4_ram3,size=512M,share=on -object memory-backend-file,id=ram1,mem-path=/dev/shm/my_m4_ram,size=512K,share=on -global cortexm-soc.shram_backend=ram1  -global cortexm-soc.ram_baseaddr=0x20000000  -global cortexm-soc.shram_baseaddr=0x30000000 -cpu cortex-m4 -kernel ../ws/gs3.bin -serial stdio -nographic -gdb tcp::1235 -S
# run --plugin ./tests/tcg/plugins/libvirtual.so,logger=ws/log_config.txt,virtual=ws/virtuals.txt,detour=ws/detours.txt,modifier=ws/modifiers.txt,args=ws/rand_setting.json,outs=ws/out_setting.json,basicblocks=ws/bb.txt -d in_asm,op -D qemu.log -machine cortexm,memory-backend=ram0 -monitor telnet:127.0.0.1:5555,server,nowait -semihosting --semihosting-config enable=on,target=native -qmp unix:/tmp/qmp-sock,server,nowait -object memory-backend-file,id=ram0,mem-path=/dev/shm/my_m4_ram3,size=512M,share=on -object memory-backend-file,id=ram1,mem-path=/dev/shm/my_m4_ram,size=512K,share=on -global cortexm-soc.shram_backend=ram1  -global cortexm-soc.ram_baseaddr=0x20000000  -global cortexm-soc.shram_baseaddr=0x30000000 -cpu cortex-m4 -kernel ../ws/gs3_new.elf -serial stdio -nographic -gdb tcp::1235 -S
# run --plugin ./tests/tcg/plugins/libvirtual.so,logger=ws/log_config.txt,virtual=ws/virtuals.txt,detour=ws/detours.txt,modifier=ws/modifiers.txt,args=ws/rand_setting.json,outs=ws/out_setting.json,basicblocks=ws/bb.txt -d in_asm,op -D qemu.log -machine cortexm,memory-backend=ram0 -monitor telnet:127.0.0.1:5555,server,nowait -semihosting --semihosting-config enable=on,target=native -qmp unix:/tmp/qmp-sock,server,nowait -object memory-backend-file,id=ram0,mem-path=/dev/shm/my_m4_ram3,size=512M,share=on -object memory-backend-file,id=ram1,mem-path=/dev/shm/my_m4_ram,size=512K,share=on -global cortexm-soc.shram_backend=ram1  -global cortexm-soc.ram_baseaddr=0x20000000  -global cortexm-soc.shram_baseaddr=0x30000000 -cpu cortex-m7 -device loader,file=../ws/gs3.bin,addr=0x08000000 -global armv7m.init-nsvtor=0x08000000 -serial stdio -nographic -gdb tcp::1235 -S
run -d in_asm,op -D qemu.log -machine cortexm,memory-backend=ram0 -monitor telnet:127.0.0.1:5555,server,nowait -semihosting --semihosting-config enable=on,target=native -qmp unix:/tmp/qmp-sock,server,nowait -object memory-backend-file,id=ram0,mem-path=/dev/shm/my_m4_ram3,size=512M,share=on -object memory-backend-file,id=ram1,mem-path=/dev/shm/my_m4_ram,size=512K,share=on -global cortexm-soc.shram_backend=ram1  -global cortexm-soc.ram_baseaddr=0x20000000  -global cortexm-soc.shram_baseaddr=0x30000000 -cpu cortex-m7 -device loader,file=../ws/gs3.bin,addr=0x08000000 -global armv7m.init-nsvtor=0x08000000 -serial stdio -nographic -gdb tcp::1235 -S
